buildscript {
  repositories {
    mavenCentral()
    gradlePluginPortal()
    google()
  }
}

allprojects {
  apply plugin: 'eclipse'
  apply plugin: 'idea'

  // This allows you to "Build and run using IntelliJ IDEA", an option in IDEA's Settings.
  idea {
    module {
      outputDir = file('build/classes/java/main')
      testOutputDir = file('build/classes/java/test')
    }
  }
}

configure(subprojects) {
  apply plugin: 'java-library'

  java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
  }

  compileJava {
    options.incremental = true
    options.encoding = 'UTF-8'
  }
  compileTestJava {
    options.encoding = 'UTF-8'
  }
}

subprojects {
  version = "$projectVersion"
  ext.appName = '20MinTillDawn'
  repositories {
    mavenCentral()
    maven { url = 'https://s01.oss.sonatype.org/content/repositories/snapshots/' }
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
  }
}

eclipse.project.name = '20MinTillDawn' + '-parent'
